spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      # url: jdbc:h2:mem:docker-web
      url: jdbc:h2:file:./db/docker-web
      driver-class-name: org.h2.Driver
      schema: classpath:db/docker-web.sql
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
repository:
  serverAddress: registry.cn-hangzhou.aliyuncs.com
  userName: 15291418231
  password: lhl123456an+
  email: 15291418231@163.com
  namespace: zouchanglin

docker:
  docker-ip: 192.168.2.2
  docker-port: 2375
project:
  url: 192.168.2.2:8080